name: PRs 

on: 
  pull_request: 
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs: 
  check-and-test: 
    name: Check and Test
    runs-on: ubuntu-22.04

    permissions: 
      contents: write  

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setup pnpm    
        uses: pnpm/action-setup@v4
        with: 
           run_install: false
      - name: Setup node      
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check, format and test
        run: pnpm check
      - name: Commit automated format changes 
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: 'ci: apply automated changes'
          branch: ${{ github.head_ref }}  
