name: Release package

on: 
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs: 
  release: 
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setup pnpm    
        uses: pnpm/action-setup@v4
        with: 
          run_install: false
      - name: Setup node      
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check, format, test and build
        run: pnpm check-and-build
      - name: Create release pull request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release new package version
          commit: "ci: release new package version"
          createGithubReleases: true
          publish: pnpm release-package
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        # This step will push tags to the repository after the package is published and will create a new release on Github
      - name: Push git tag after publish
        if: steps.changesets.outputs.published == 'true'
        run: git push --follow-tags     
  